// GitHub plumbing via the gh CLI: sticky PR comment, publishing bundles to
// the orphan `screenmaps` branch, and opening a flows PR against main.
import { execFileSync, spawnSync } from 'node:child_process'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { sh, log, ensureDir } from './util.mjs'

const gh = (args, opts = {}) => sh('gh', args, opts)

export function repoSlug() {
  if (process.env.GITHUB_REPOSITORY) return process.env.GITHUB_REPOSITORY
  return gh(['repo', 'view', '--json', 'nameWithOwner', '-q', '.nameWithOwner'])
}

export const MARKER = '<!-- screenmap-ci -->'

export function upsertStickyComment({ repo, number, body }) {
  const comments = JSON.parse(gh(['api', `repos/${repo}/issues/${number}/comments`, '--paginate']))
  const mine = comments.find((c) => typeof c.body === 'string' && c.body.includes(MARKER))
  const payload = JSON.stringify({ body: `${MARKER}\n${body}` })
  const tmp = path.join(os.tmpdir(), `screenmap-comment-${Date.now()}.json`)
  fs.writeFileSync(tmp, payload)
  if (mine) gh(['api', '-X', 'PATCH', `repos/${repo}/issues/comments/${mine.id}`, '--input', tmp])
  else gh(['api', '-X', 'POST', `repos/${repo}/issues/${number}/comments`, '--input', tmp])
  fs.rmSync(tmp, { force: true })
  return mine ? 'updated' : 'created'
}

// Commit files into an orphan branch via a throwaway worktree. Returns the
// new commit sha and SHA-pinned raw URLs (raw.githubusercontent caches ~5min
// and jsDelivr ~12h on branch refs — pin to the commit).
export function publishToBranch({ repo, branch = 'screenmaps', files, message, cwd = process.cwd() }) {
  const wt = fs.mkdtempSync(path.join(os.tmpdir(), 'screenmaps-'))
  const git = (args, o = {}) => sh('git', args, { cwd, ...o })
  const exists = spawnSync('git', ['ls-remote', '--exit-code', '--heads', 'origin', branch], { cwd, encoding: 'utf8' }).status === 0
  if (exists) {
    git(['fetch', '--depth', '1', 'origin', branch])
    git(['worktree', 'add', wt, `origin/${branch}`])
    sh('git', ['checkout', '-B', branch], { cwd: wt })
  } else {
    git(['worktree', 'add', '--detach', wt])
    sh('git', ['checkout', '--orphan', branch], { cwd: wt })
    sh('git', ['rm', '-rfq', '.'], { cwd: wt })
    fs.writeFileSync(path.join(wt, 'README.md'), '# screenmaps\n\nGenerated by screenmap-ci: baseline maps per commit and per-PR change bundles. Not for humans to edit.\n')
  }
  for (const { src, dest } of files) { ensureDir(path.dirname(path.join(wt, dest))); fs.copyFileSync(src, path.join(wt, dest)) }
  sh('git', ['add', '-A'], { cwd: wt })
  const authored = spawnSync('git', ['-c', 'user.name=screenmap-ci', '-c', 'user.email=screenmap-ci@users.noreply.github.com', 'commit', '-q', '-m', message], { cwd: wt, encoding: 'utf8' })
  if (authored.status !== 0 && !/nothing to commit/.test(authored.stdout + authored.stderr)) throw new Error(authored.stderr)
  sh('git', ['push', '-q', 'origin', `HEAD:${branch}`], { cwd: wt })
  const sha = sh('git', ['rev-parse', 'HEAD'], { cwd: wt })
  git(['worktree', 'remove', '--force', wt])
  const base = `https://raw.githubusercontent.com/${repo}/${sha}`
  const urls = Object.fromEntries(files.map((f) => [f.dest, `${base}/${f.dest}`]))
  log(`published ${files.length} file(s) to ${branch}@${sha.slice(0, 7)}`)
  return { sha, base, urls }
}

export function openFlowsPR({ repo, base = 'main', flowsSrcDir, flowsDestDir = '.screenmap/flows', title, body, cwd = process.cwd() }) {
  const files = fs.existsSync(flowsSrcDir) ? fs.readdirSync(flowsSrcDir).filter((f) => f.endsWith('.yaml') || f.endsWith('.meta.json')) : []
  if (!files.length) return null
  const branch = `screenmap/flows-${Date.now().toString(36)}`
  const git = (args) => sh('git', args, { cwd })
  git(['fetch', '--depth', '1', 'origin', base])
  git(['checkout', '-B', branch, `origin/${base}`])
  ensureDir(path.join(cwd, flowsDestDir))
  for (const f of files) fs.copyFileSync(path.join(flowsSrcDir, f), path.join(cwd, flowsDestDir, f))
  git(['add', flowsDestDir])
  execFileSync('git', ['-c', 'user.name=screenmap-ci', '-c', 'user.email=screenmap-ci@users.noreply.github.com', 'commit', '-q', '-m', title], { cwd })
  git(['push', '-q', '-u', 'origin', branch])
  const url = gh(['pr', 'create', '--repo', repo, '--base', base, '--head', branch, '--title', title, '--body', body])
  log(`opened flows PR: ${url}`)
  return url
}
